force-app/main/default/objects/Booth__c/Booth__c.object-meta.xml
<CustomObject>
    <label>Festival Booth</label>
    <nameField>
        <displayFormat>BOOTH-{0000}</displayFormat>
        <label>Booth Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Festival Booths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booth__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Main_Square</fullName>
                <label>Main Square</label>
            </value>
            <value>
                <fullName>Treat_Lane</fullName>
                <label>Treat Lane</label>
            </value>
            <value>
                <fullName>Sweet_Corner</fullName>
                <label>Sweet Corner</label>
            </value>
            <value>
                <fullName>Festival Row</fullName>
                <label>Festival_Row</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booth__c/fields/Safety_Rating__c.field-meta.xml
<CustomField>
    <fullName>Safety_Rating__c</fullName>
    <description>To track the safety level of a booth&apos;s setup and operations</description>
    <inlineHelpText>To track the safety level of a booth&apos;s setup and operations</inlineHelpText>
    <label>Safety Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 = Critical issues (needs immediate attention)</fullName>
            </value>
            <value>
                <fullName>2 = Major concerns</fullName>
            </value>
            <value>
                <fullName>3 = Minor issues</fullName>
            </value>
            <value>
                <fullName>4 = Good standing</fullName>
            </value>
            <value>
                <fullName>5 = Excellent/Perfect safety record</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booth__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Festival Booths</relationshipLabel>
    <relationshipName>Festival_Booths</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>Camp Apex Advent of Salesforce Development. This object is used to represent vendors who would like a booth at the festival.</description>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baker</fullName>
            </value>
            <value>
                <fullName>Candy Maker</fullName>
            </value>
            <value>
                <fullName>Performer</fullName>
            </value>
            <value>
                <fullName>Game Master</fullName>
            </value>
            <value>
                <fullName>Fisherelf</fullName>
            </value>
            <value>
                <fullName>Ranger</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BoothHelperClass.cls
public with sharing class BoothHelperClass {
    public static void creationInspectionTask(List<Booth__c> boothList){
        List<Task> taskToCreate = new List<Task>();
        if(!boothList.isEmpty()){
            for(Booth__c booth : boothList){
                Task newTask = new Task();
                if(booth.Safety_Rating__c == '1 = Critical issues (needs immediate attention)'){
                    newTask.OwnerId = booth.OwnerId;
                    newTask.Subject = 'URGENT: Critical Safety Inspection Required';
                    newTask.WhatId = booth.Id;
                    newTask.ActivityDate = Date.today() + 1;
                    newTask.Priority = 'High';
                }else if(booth.Safety_Rating__c == '2 = Major concerns'){
                    newTask.OwnerId = booth.OwnerId;
                    newTask.Subject = 'Safety Concerns Need Review';
                    newTask.WhatId = booth.Id;
                    newTask.ActivityDate = Date.today() + 2;
                    newTask.Priority = 'High';
                }else if(booth.Safety_Rating__c == '3 = Minor issues'){
                    newTask.OwnerId = booth.OwnerId;
                    newTask.Subject = 'Safety Review Required';
                    newTask.WhatId = booth.Id;
                    newTask.ActivityDate = Date.today() + 3;
                    newTask.Priority = 'Normal';
                }

                taskToCreate.add(newTask);
            }
        }

        if(!taskToCreate.isEmpty()){
            insert taskToCreate;
        }
    }

    /*
    public static void locationValidation(List<Booth__c> boothList) {
        Map<Id, Booth__c> vendorIdBoothMap = new Map<Id, Booth__c>();
    
        // Populate the map to associate Vendor Ids with Booths
        for (Booth__c booth : boothList) {
            if (booth.Vendor__c != null) {
                vendorIdBoothMap.put(booth.Vendor__c, booth);
            }
        }
    
        String errorMessage = 'The Booth may not be placed in this location.';
        
        // Query Vendors associated with Booths
        if (!vendorIdBoothMap.isEmpty()) {
            List<Vendor__c> vendorList = [SELECT Id, Type__c FROM Vendor__c WHERE Id IN :vendorIdBoothMap.keySet()];
            
            // Iterate over Vendors and validate Booth locations
            for (Vendor__c vendor : vendorList) {
                Booth__c booth = vendorIdBoothMap.get(vendor.Id); // Get the booth for this vendor
                
                if (booth != null) {
                    if (vendor.Type__c == 'Baker' && (booth.Location__c != 'Main Square' && booth.Location__c != 'Treat Lane')) {
                        booth.addError(errorMessage);
                    } else if (vendor.Type__c == 'Candy Maker' && booth.Location__c != 'Sweet Corner') {
                        booth.addError(errorMessage);
                    } else if (vendor.Type__c == 'Game Master' && (booth.Location__c != 'Treat Lane' && booth.Location__c != 'Main Square')) {
                        booth.addError(errorMessage);
                    }
                }
            }
        }
    }    
    */
}