force-app/main/default/objects/Booth__c/Booth__c.object-meta.xml
<CustomObject>
    <label>Festival Booth</label>
    <nameField>
        <displayFormat>BOOTH-{0000}</displayFormat>
        <label>Booth Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Festival Booths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booth__c/fields/Inspection_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Frequency__c</fullName>
    <label>Inspection Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Every 2 hours</fullName>
            </value>
            <value>
                <fullName>Every 4 hours</fullName>
            </value>
            <value>
                <fullName>Every 6 hours</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booth__c/fields/Safety_Rating__c.field-meta.xml
<CustomField>
    <fullName>Safety_Rating__c</fullName>
    <description>To track the safety level of a booth&apos;s setup and operations</description>
    <inlineHelpText>To track the safety level of a booth&apos;s setup and operations</inlineHelpText>
    <label>Safety Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 = Critical issues (needs immediate attention)</fullName>
            </value>
            <value>
                <fullName>2 = Major concerns</fullName>
            </value>
            <value>
                <fullName>3 = Minor issues</fullName>
            </value>
            <value>
                <fullName>4 = Good standing</fullName>
            </value>
            <value>
                <fullName>5 = Excellent/Perfect safety record</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booth__c/fields/Setup_Date__c.field-meta.xml
<CustomField>
    <fullName>Setup_Date__c</fullName>
    <label>Setup Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booth__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
            </value>
            <value>
                <fullName>Operating</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booth__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Festival Booths</relationshipLabel>
    <relationshipName>Festival_Booths</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Permit__c/Permit__c.object-meta.xml
<CustomObject>
    <description>Camp Apex Advent of Salesforce Development. This object is used to help vendors book a booth.</description>
    <label>Permit</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Permit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Permit__c/fields/Booth_Type__c.field-meta.xml
<CustomField>
    <fullName>Booth_Type__c</fullName>
    <label>Booth Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Sweets</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Games</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Permit__c/fields/Equipment_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Requirements__c</fullName>
    <label>Equipment Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard (Basic Booth Setup)</fullName>
            </value>
            <value>
                <fullName>Premium (Enhanced Power/Water)</fullName>
            </value>
            <value>
                <fullName>Specialty (Custom Requirements)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Permit__c/fields/Space_Required__c.field-meta.xml
<CustomField>
    <fullName>Space_Required__c</fullName>
    <inlineHelpText>The amount of space the Booth will take up at the festival</inlineHelpText>
    <label>Space Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Extra-Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Permit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Permit__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Permits</relationshipLabel>
    <relationshipName>Permits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <description>Camp Apex Advent of Salesforce Development. This object is used to represent vendors who would like a booth at the festival.</description>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PermitHelperClass.cls
public with sharing class PermitHelperClass {

    /*public static void applicationPending(List<Permit__c> permList){

        Set<Id> vendorIds = new Set<Id>();
        Map<Id, Integer> permitCountMap = new Map<Id, Integer>();
        Map<Id, List<Permit__c>> multiplePermitMap = new Map<Id, List<Permit__c>>();
        if(!permList.isEmpty()){
            for(Permit__c perm: permList){
                //vendorIds.add(perm.Vendor__c);
                if(!permitCountMap.containsKey(perm.Vendor__c)){
                    permitCountMap.put(perm.Vendor__c, 1);
                }else{
                    Integer count = permitCountMap.get(perm.Vendor__c);
                    permitCountMap.put(perm.Vendor__c, count + 1);
                }
            }

            for(Id vendorId : permitCountMap.keySet()){
                if(permitCountMap.get(vendorId) > 1){
                    List<Permit__c> multiplePerm = new List<Permit__c>();
                    for(Permit__c perm : permList){
                        if(perm.Vendor__c == vendorId){
                            multiplePerm.add(perm);
                        }
                    }
                    multiplePermitMap.put(vendorId, multiplePerm);
                }else{
                    vendorIds.add(vendorId);
                }
            }
        }
        if(!multiplePermitMap.isEmpty()){
            for(Id venId : multiplePermitMap.keySet()){
                for(Permit__c perms : multiplePermitMap.get(venId)){
                    perms.addError('Vendor has an existing permit application in process');
                }
            }
        }
        Map<Id, List<Permit__c>> vendorPermMap = new Map<Id, List<Permit__c>>();
        if(!vendorIds.isEmpty()){
            List<Permit__c> existingPermList = [Select Id, Vendor__c, Status__c From Permit__c where Vendor__c in : vendorIds and Status__c != 'Rejected'];
            
            for(Permit__c perm : existingPermList){
                if(!vendorPermMap.containsKey(perm.Vendor__c)){
                    List<Permit__c> existPerm = new List<Permit__c>();
                    existPerm.add(perm);
                    vendorPermMap.put(perm.Vendor__c, existPerm);
                }else{
                    vendorPermMap.get(perm.Vendor__c).add(perm);
                }
            }
        }
        List<Permit__c> permListToInsert = new List<Permit__c>();
        if(!vendorPermMap.isEmpty()){
            for(Permit__c perm : permList){
                if(vendorPermMap.containsKey(perm.Vendor__c)){
                    perm.Vendor__c.addError('Vendor has an existing permit application in process');
                }else{
                    permListToInsert.add(perm);
                }
            }
        }
    }
    */

    public static void boothCreationOnApproval(List<Permit__c> newPermList, Map<Id, Permit__c> oldPermMap) {
        List<Booth__c> boothToInsert = new List<Booth__c>();
        List<Permit__c> approvedPermits = new List<Permit__c>();
    
        for (Permit__c newPerm : newPermList) {
           
            if (newPerm.Status__c == 'Approved') {
                Permit__c oldPermit = new Permit__c();
                if(oldPermMap != null){
                    oldPermit = oldPermMap.get(newPerm.Id);
                    if(oldPermit.Status__c != 'Approved'){
                        approvedPermits.add(newPerm);
                    }
                }
                approvedPermits.add(newPerm);
            }
        }
        
        if(!approvedPermits.isEmpty()){
            for(Permit__c perm : approvedPermits){
                Booth__c newBooth = new Booth__c();
                newBooth.Status__c = 'Setup';
                newBooth.Setup_Date__c = Date.today();
                newBooth.Vendor__c = perm.Vendor__c;
                if(perm.Risk_Level__c == 'High'){
                    newBooth.Safety_Rating__c = '1 = Critical issues (needs immediate attention)';
                    newBooth.Inspection_Frequency__c = 'Every 2 hours';
                }else if(perm.Equipment_Requirements__c == 'Specialty (Custom Requirements)' && perm.Space_Required__c == 'Extra-Large'){
                    newBooth.Safety_Rating__c = '2 = Major concerns';
                    newBooth.Inspection_Frequency__c = 'Every 4 hours';
                }else if((perm.Booth_Type__c == 'Food' || perm.Booth_Type__c == 'Sweets') && perm.Equipment_Requirements__c == 'Premium (Enhanced Power/Water)'){
                    newBooth.Safety_Rating__c = '3 = Minor issues';
                    newBooth.Inspection_Frequency__c = 'Every 6 hours';
                }else{
                    newBooth.Safety_Rating__c = '4 = Good Standing';
                    newBooth.Inspection_Frequency__c = 'Daily';
                }
                boothToInsert.add(newBooth); 
            }
        }
        List<Permit__c> permitsToUpdatewithBooth = new List<Permit__c>();
        if (!boothToInsert.isEmpty()) {
            insert boothToInsert;
        }
    }
}